
package Vista;

import static Controlador.Main.apellido;
import static Controlador.Main.frmMenu;
import static Controlador.Main.nombre;
import Controlador.RegistroBalance;
import Controlador.Fecha;
import Modelo.Balance;
import Modelo.BalanceSQL;
import static Vista.Menu.frmMinimenu;
import static Vista.Menu.frmPerfil;
import java.time.LocalDateTime;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ARANAGA
 */
public class BalanceGeneral extends javax.swing.JFrame {
    
    Balance modeloBalance = new Balance();
    BalanceSQL modeloBalanceSQL = new BalanceSQL();
    RegistroBalance balance = new RegistroBalance();
    Fecha fecha = new Fecha();
    
    int año = 0, mes = 0;
    boolean primera_entrada = true;
    
    public BalanceGeneral() {
        initComponents();
        setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imágenes/Ícono del Programa.png")).getImage());
        llenarCajaTexto();
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBoxMes = new javax.swing.JComboBox();
        jComboBoxAño = new javax.swing.JComboBox();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldDMD = new javax.swing.JTextField();
        jTextFieldDAD = new javax.swing.JTextField();
        jTextFieldTID = new javax.swing.JTextField();
        jTextFieldDMBs = new javax.swing.JTextField();
        jTextFieldDABs = new javax.swing.JTextField();
        jTextFieldTIBs = new javax.swing.JTextField();
        jTextFieldAseoD = new javax.swing.JTextField();
        jTextFieldAseoBs = new javax.swing.JTextField();
        jTextFieldVID = new javax.swing.JTextField();
        jTextFieldVIB = new javax.swing.JTextField();
        jTextFieldVED = new javax.swing.JTextField();
        jTextFieldVEBs = new javax.swing.JTextField();
        jTextFieldCE1D = new javax.swing.JTextField();
        jTextFieldCE1Bs = new javax.swing.JTextField();
        jTextFieldCE2D = new javax.swing.JTextField();
        jTextFieldCE2Bs = new javax.swing.JTextField();
        jTextFieldCE3D = new javax.swing.JTextField();
        jTextFieldCE3Bs = new javax.swing.JTextField();
        jTextFieldTGD = new javax.swing.JTextField();
        jTextFieldTGBs = new javax.swing.JTextField();
        jTextFieldSaldoD = new javax.swing.JTextField();
        jTextFieldSaldoBs = new javax.swing.JTextField();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldUsuarioBienvenida = new javax.swing.JTextField();
        jButtonCerrar = new javax.swing.JButton();
        jButtonMinimizar = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jButtonPerfil = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxMes.setBackground(new java.awt.Color(240, 240, 240));
        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBoxMes.setBorder(null);
        jComboBoxMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMesItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 680, 120, 30));

        jComboBoxAño.setBackground(new java.awt.Color(240, 240, 240));
        jComboBoxAño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031" }));
        jComboBoxAño.setBorder(null);
        jComboBoxAño.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxAñoItemStateChanged(evt);
            }
        });
        jComboBoxAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAñoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 678, 120, 30));

        jTextFieldUsuario.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUsuario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldUsuario.setBorder(null);
        jPanel1.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 180, 30));

        jTextFieldDMD.setForeground(new java.awt.Color(116, 116, 116));
        jTextFieldDMD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDMD.setBorder(null);
        jPanel1.add(jTextFieldDMD, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 176, 140, -1));

        jTextFieldDAD.setForeground(new java.awt.Color(116, 116, 116));
        jTextFieldDAD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDAD.setBorder(null);
        jPanel1.add(jTextFieldDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 140, -1));

        jTextFieldTID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldTID.setForeground(new java.awt.Color(0, 181, 81));
        jTextFieldTID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTID.setBorder(null);
        jPanel1.add(jTextFieldTID, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 220, 140, -1));

        jTextFieldDMBs.setForeground(new java.awt.Color(116, 116, 116));
        jTextFieldDMBs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDMBs.setBorder(null);
        jPanel1.add(jTextFieldDMBs, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 140, 20));

        jTextFieldDABs.setForeground(new java.awt.Color(116, 116, 116));
        jTextFieldDABs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDABs.setBorder(null);
        jPanel1.add(jTextFieldDABs, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 264, 140, 20));

        jTextFieldTIBs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldTIBs.setForeground(new java.awt.Color(0, 181, 81));
        jTextFieldTIBs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTIBs.setBorder(null);
        jPanel1.add(jTextFieldTIBs, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 140, -1));

        jTextFieldAseoD.setForeground(new java.awt.Color(116, 116, 116));
        jTextFieldAseoD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAseoD.setBorder(null);
        jPanel1.add(jTextFieldAseoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 140, 20));

        jTextFieldAseoBs.setForeground(new java.awt.Color(116, 116, 116));
        jTextFieldAseoBs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAseoBs.setBorder(null);
        jPanel1.add(jTextFieldAseoBs, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 336, 140, -1));

        jTextFieldVID.setForeground(new java.awt.Color(116, 116, 116));
        jTextFieldVID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldVID.setBorder(null);
        jPanel1.add(jTextFieldVID, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 354, 140, 20));

        jTextFieldVIB.setForeground(new java.awt.Color(116, 116, 116));
        jTextFieldVIB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldVIB.setBorder(null);
        jTextFieldVIB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVIBActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldVIB, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 140, -1));

        jTextFieldVED.setForeground(new java.awt.Color(116, 116, 116));
        jTextFieldVED.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldVED.setBorder(null);
        jPanel1.add(jTextFieldVED, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 140, 20));

        jTextFieldVEBs.setForeground(new java.awt.Color(116, 116, 116));
        jTextFieldVEBs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldVEBs.setBorder(null);
        jTextFieldVEBs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVEBsActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldVEBs, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 426, 140, -1));

        jTextFieldCE1D.setForeground(new java.awt.Color(116, 116, 116));
        jTextFieldCE1D.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCE1D.setBorder(null);
        jPanel1.add(jTextFieldCE1D, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 140, -1));

        jTextFieldCE1Bs.setForeground(new java.awt.Color(116, 116, 116));
        jTextFieldCE1Bs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCE1Bs.setBorder(null);
        jPanel1.add(jTextFieldCE1Bs, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 468, 140, 20));

        jTextFieldCE2D.setForeground(new java.awt.Color(116, 116, 116));
        jTextFieldCE2D.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCE2D.setBorder(null);
        jPanel1.add(jTextFieldCE2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 140, 20));

        jTextFieldCE2Bs.setForeground(new java.awt.Color(116, 116, 116));
        jTextFieldCE2Bs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCE2Bs.setBorder(null);
        jPanel1.add(jTextFieldCE2Bs, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 514, 140, 20));

        jTextFieldCE3D.setForeground(new java.awt.Color(116, 116, 116));
        jTextFieldCE3D.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCE3D.setBorder(null);
        jPanel1.add(jTextFieldCE3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 140, -1));

        jTextFieldCE3Bs.setForeground(new java.awt.Color(116, 116, 116));
        jTextFieldCE3Bs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCE3Bs.setBorder(null);
        jPanel1.add(jTextFieldCE3Bs, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 140, -1));

        jTextFieldTGD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldTGD.setForeground(new java.awt.Color(0, 181, 81));
        jTextFieldTGD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTGD.setBorder(null);
        jPanel1.add(jTextFieldTGD, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 584, 140, -1));

        jTextFieldTGBs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldTGBs.setForeground(new java.awt.Color(0, 181, 81));
        jTextFieldTGBs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTGBs.setBorder(null);
        jPanel1.add(jTextFieldTGBs, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 604, 140, 20));

        jTextFieldSaldoD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldSaldoD.setForeground(new java.awt.Color(0, 181, 81));
        jTextFieldSaldoD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSaldoD.setBorder(null);
        jPanel1.add(jTextFieldSaldoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 630, 140, -1));

        jTextFieldSaldoBs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldSaldoBs.setForeground(new java.awt.Color(0, 181, 81));
        jTextFieldSaldoBs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSaldoBs.setBorder(null);
        jPanel1.add(jTextFieldSaldoBs, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 650, 140, 20));

        jTextFieldTitulo.setFont(new java.awt.Font("Microsoft JhengHei", 0, 28)); // NOI18N
        jTextFieldTitulo.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldTitulo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldTitulo.setBorder(null);
        jTextFieldTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 240, 40));

        jTextFieldUsuarioBienvenida.setFont(new java.awt.Font("Microsoft JhengHei", 0, 28)); // NOI18N
        jTextFieldUsuarioBienvenida.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUsuarioBienvenida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldUsuarioBienvenida.setText("Balance General -                   ");
        jTextFieldUsuarioBienvenida.setBorder(null);
        jTextFieldUsuarioBienvenida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextFieldUsuarioBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 550, 40));

        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Cerrar.png"))); // NOI18N
        jButtonCerrar.setBorder(null);
        jButtonCerrar.setContentAreaFilled(false);
        jButtonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 10, 10, 20));

        jButtonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Minimizar.png"))); // NOI18N
        jButtonMinimizar.setBorder(null);
        jButtonMinimizar.setContentAreaFilled(false);
        jButtonMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 17, 20, 10));

        jButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Menú.png"))); // NOI18N
        jButtonMenu.setBorder(null);
        jButtonMenu.setContentAreaFilled(false);
        jButtonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, -1, 40, 50));

        jButtonPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Perfil (Sesión Actual).png"))); // NOI18N
        jButtonPerfil.setBorder(null);
        jButtonPerfil.setContentAreaFilled(false);
        jButtonPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 3, 50, 40));

        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Tablas/Botón Regresar.png"))); // NOI18N
        jButtonRegresar.setBorder(null);
        jButtonRegresar.setContentAreaFilled(false);
        jButtonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Tablas/Botón Regresar (Presionado).png"))); // NOI18N
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 40, 40));

        jLabelFondo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFondo.setForeground(new java.awt.Color(0, 181, 81));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/3. Balance General/Balance General_1.png"))); // NOI18N
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        frmMinimenu.setVisible(true);
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizarActionPerformed
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizarActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        this.dispose();
        frmMenu.setVisible(true);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jTextFieldVIBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVIBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVIBActionPerformed

    private void jTextFieldVEBsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVEBsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVEBsActionPerformed

    private void jButtonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerfilActionPerformed
        frmPerfil.setVisible(true);
    }//GEN-LAST:event_jButtonPerfilActionPerformed

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jComboBoxAñoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxAñoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAñoItemStateChanged

    private void jComboBoxMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMesItemStateChanged
        if(!primera_entrada){actualizarBalance();}
    }//GEN-LAST:event_jComboBoxMesItemStateChanged

    private void jComboBoxAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAñoActionPerformed
        if(!primera_entrada){actualizarBalance();}
    }//GEN-LAST:event_jComboBoxAñoActionPerformed
    
    private void inicializar(){
        LocalDateTime Fecha = LocalDateTime.now();
        
        año = Fecha.getYear();
        mes = Fecha.getMonthValue();
        
        modeloBalance.setAño(año);
        modeloBalance.setMes(mes);
        
        jComboBoxAño.setSelectedIndex(año-2021);
        jComboBoxMes.setSelectedIndex(mes-1);

        balance.registrarIngresos();
        
        if(modeloBalanceSQL.buscar(modeloBalance)){
            jTextFieldTitulo.setText(fecha.nombreMes(mes)+" "+año);
            cargarBalance();
            primera_entrada = false;
        }
    }
    
    private void actualizarBalance(){
        String añoS = jComboBoxAño.getSelectedItem().toString();
        
        año = Integer.parseInt(añoS);
        mes = jComboBoxMes.getSelectedIndex() + 1;
        
        modeloBalance.setAño(año);
        modeloBalance.setMes(mes);
        
        if(modeloBalanceSQL.buscar(modeloBalance)){
            jTextFieldTitulo.setText(fecha.nombreMes(mes)+" "+año);
            cargarBalance();
        }
        else{
            JOptionPane.showMessageDialog(null, "No existe un balance general "
                    + "de la fecha seleccionada. Intente nuevamente");
        }
    }
    
    private void cargarBalance(){
        jTextFieldDMD.setText(String.valueOf(modeloBalance.getDeuda_morosa_dolares()));
        jTextFieldDAD.setText(String.valueOf(modeloBalance.getDeuda_actual_dolares()));
        jTextFieldTID.setText(String.valueOf(modeloBalance.getTotal_ingresos_dolares()));
        jTextFieldDMBs.setText(String.valueOf(modeloBalance.getDeuda_morosa_bolivares()));
        jTextFieldDABs.setText(String.valueOf(modeloBalance.getDeuda_morosa_bolivares()));
        jTextFieldTIBs.setText(String.valueOf(modeloBalance.getTotal_ingresos_bolivares()));
        jTextFieldAseoD.setText(String.valueOf(modeloBalance.getAseo_dolares()));
        jTextFieldAseoBs.setText(String.valueOf(modeloBalance.getAseo_bolivares()));
        jTextFieldVID.setText(String.valueOf(modeloBalance.getVigilancia_interna_dolares()));
        jTextFieldVIB.setText(String.valueOf(modeloBalance.getVigilancia_interna_bolivares()));
        jTextFieldVED.setText(String.valueOf(modeloBalance.getVigilancia_externa_dolares()));
        jTextFieldVEBs.setText(String.valueOf(modeloBalance.getVigilancia_externa_bolivares()));
        jTextFieldCE1D.setText(String.valueOf(modeloBalance.getCuota_especial1_dolares()));
        jTextFieldCE1Bs.setText(String.valueOf(modeloBalance.getCuota_especial1_bolivares()));
        jTextFieldCE2D.setText(String.valueOf(modeloBalance.getCuota_especial2_dolares()));
        jTextFieldCE2Bs.setText(String.valueOf(modeloBalance.getCuota_especial2_bolivares()));
        jTextFieldCE3D.setText(String.valueOf(modeloBalance.getCuota_especial3_dolares()));
        jTextFieldCE3Bs.setText(String.valueOf(modeloBalance.getCuota_especial3_bolivares()));
        jTextFieldTGD.setText(String.valueOf(modeloBalance.getTotal_egresos_dolares()));
        jTextFieldTGBs.setText(String.valueOf(modeloBalance.getTotal_egresos_bolivares()));
        jTextFieldSaldoD.setText(String.valueOf(modeloBalance.getSaldo_dolares()));
        jTextFieldSaldoBs.setText(String.valueOf(modeloBalance.getSaldo_bolivares()));
    }
   
    public void llenarCajaTexto(){
        jTextFieldUsuario.setText(nombre+" "+apellido);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalanceGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonMinimizar;
    private javax.swing.JButton jButtonPerfil;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JComboBox jComboBoxAño;
    private javax.swing.JComboBox jComboBoxMes;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAseoBs;
    private javax.swing.JTextField jTextFieldAseoD;
    private javax.swing.JTextField jTextFieldCE1Bs;
    private javax.swing.JTextField jTextFieldCE1D;
    private javax.swing.JTextField jTextFieldCE2Bs;
    private javax.swing.JTextField jTextFieldCE2D;
    private javax.swing.JTextField jTextFieldCE3Bs;
    private javax.swing.JTextField jTextFieldCE3D;
    private javax.swing.JTextField jTextFieldDABs;
    private javax.swing.JTextField jTextFieldDAD;
    private javax.swing.JTextField jTextFieldDMBs;
    private javax.swing.JTextField jTextFieldDMD;
    private javax.swing.JTextField jTextFieldSaldoBs;
    private javax.swing.JTextField jTextFieldSaldoD;
    private javax.swing.JTextField jTextFieldTGBs;
    private javax.swing.JTextField jTextFieldTGD;
    private javax.swing.JTextField jTextFieldTIBs;
    private javax.swing.JTextField jTextFieldTID;
    private javax.swing.JTextField jTextFieldTitulo;
    public javax.swing.JTextField jTextFieldUsuario;
    public javax.swing.JTextField jTextFieldUsuarioBienvenida;
    private javax.swing.JTextField jTextFieldVEBs;
    private javax.swing.JTextField jTextFieldVED;
    private javax.swing.JTextField jTextFieldVIB;
    private javax.swing.JTextField jTextFieldVID;
    // End of variables declaration//GEN-END:variables
}
