
package Vista;

import Controlador.Fecha;
import static Controlador.Main.apellido;
import static Controlador.Main.frmMenu;
import static Controlador.Main.nombre;
import Modelo.Conexion;
import Modelo.Cuenta;
import Modelo.CuentaSQL;
import static Vista.Menu.frmMinimenu;
import static Vista.Menu.frmPerfil;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.time.LocalDateTime;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Deuda extends javax.swing.JFrame {

    InformacionDeuda frmInformacionDeudas = new InformacionDeuda();
    Cuenta modeloCuenta = new Cuenta();
    CuentaSQL modeloCuentaSQL = new CuentaSQL();
    
    public Deuda() {
        initComponents();
        setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imágenes/Ícono del Programa.png")).getImage());
        llenarCajaTexto();
        cargarDatos(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButtonInformacion = new javax.swing.JButton();
        jButtonPerfil = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jButtonMinimizar = new javax.swing.JButton();
        jButtonCargar = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jComboBoxAño = new javax.swing.JComboBox();
        jComboBoxMes = new javax.swing.JComboBox();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldUsuario.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUsuario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 180, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 330, 460));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 560, 460));

        jButtonInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Botones Adicionales/Botón Manejar Información.png"))); // NOI18N
        jButtonInformacion.setBorder(null);
        jButtonInformacion.setContentAreaFilled(false);
        jButtonInformacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformacionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 200, 30));

        jButtonPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Perfil (Sesión Actual).png"))); // NOI18N
        jButtonPerfil.setBorder(null);
        jButtonPerfil.setContentAreaFilled(false);
        jButtonPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 3, 50, 40));

        jButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Menú.png"))); // NOI18N
        jButtonMenu.setBorder(null);
        jButtonMenu.setContentAreaFilled(false);
        jButtonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, -1, 40, 50));

        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Tablas/Botón Regresar.png"))); // NOI18N
        jButtonRegresar.setBorder(null);
        jButtonRegresar.setContentAreaFilled(false);
        jButtonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Tablas/Botón Regresar (Presionado).png"))); // NOI18N
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 40, 40));

        jButtonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Minimizar.png"))); // NOI18N
        jButtonMinimizar.setBorder(null);
        jButtonMinimizar.setContentAreaFilled(false);
        jButtonMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 17, 20, 10));

        jButtonCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Cargar Tabla.png"))); // NOI18N
        jButtonCargar.setBorder(null);
        jButtonCargar.setContentAreaFilled(false);
        jButtonCargar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 100, 20, 30));

        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Cerrar.png"))); // NOI18N
        jButtonCerrar.setBorder(null);
        jButtonCerrar.setContentAreaFilled(false);
        jButtonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 10, 10, 20));

        jLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Tablas/Nombres/Nombre Deuda General.png"))); // NOI18N
        jPanel1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 220, -1));

        jComboBoxAño.setBackground(new java.awt.Color(240, 240, 240));
        jComboBoxAño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031" }));
        jComboBoxAño.setBorder(null);
        jComboBoxAño.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxAñoItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 680, 120, 30));

        jComboBoxMes.setBackground(new java.awt.Color(240, 240, 240));
        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBoxMes.setBorder(null);
        jComboBoxMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMesItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 680, 120, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Tablas/Pantalla para Tablas.png"))); // NOI18N
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        frmMinimenu.setVisible(true);
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizarActionPerformed
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizarActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        frmInformacionDeudas.dispose();
        this.dispose();
        frmMenu.setVisible(true);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformacionActionPerformed
        frmInformacionDeudas.setVisible(true);
    }//GEN-LAST:event_jButtonInformacionActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerfilActionPerformed
        frmPerfil.setVisible(true);
    }//GEN-LAST:event_jButtonPerfilActionPerformed

    private void jComboBoxAñoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxAñoItemStateChanged
        cargarDatos(2);
    }//GEN-LAST:event_jComboBoxAñoItemStateChanged

    private void jComboBoxMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMesItemStateChanged
        cargarDatos(2);
    }//GEN-LAST:event_jComboBoxMesItemStateChanged

    private void jButtonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarActionPerformed
       cargarDatos(2);
    }//GEN-LAST:event_jButtonCargarActionPerformed
    
    private void cargarDatos(int eleccion){
        LocalDateTime fecha = LocalDateTime.now();
        int año = 0, mes = 0;
        
        switch(eleccion){
            case 1: año = fecha.getYear();
                    mes = fecha.getMonthValue();

                    jComboBoxAño.setSelectedIndex(año-2021);
                    jComboBoxMes.setSelectedIndex(mes-1);
                    break;
            case 2: año = Integer.parseInt(jComboBoxAño.getSelectedItem().toString());
                    mes = jComboBoxMes.getSelectedIndex() + 1;
                    break;
        }

        cargarTablaGeneral(año,mes);
        cargarTablaDeudas();
    }
    
    private void cargarTablaGeneral(int año, int mes){
        try{
            DefaultTableModel modelo = new DefaultTableModel();
            jTable1.setModel(modelo);
            
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            Connection con = conn.getConexion();
            

            String sql = "SELECT numero_casa4, pago_dolares, pago_bolivares,"
                    + "deuda_dolares, deuda_bolivares FROM cuenta WHERE año2 = ? AND "
                    + "mes2 = ? ORDER BY numero_casa4";
            
            ps = con.prepareStatement(sql);
            ps.setInt(1, año);
            ps.setInt(2, mes);
            rs = ps.executeQuery();

            ResultSetMetaData rsMD = rs.getMetaData();
            int cantidadColumnas = rsMD.getColumnCount();

            modelo.addColumn("Casa");
            modelo.addColumn("Pago ($)");
            modelo.addColumn("Pago (Bs)");
            modelo.addColumn("Deuda ($)");
            modelo.addColumn("Deuda (Bs)");

                while(rs.next()){
                    
                    Object[] filas = new Object[cantidadColumnas];

                    for(int i=0;i<cantidadColumnas;i++){
                        filas[i] = rs.getObject(i+1);
                    }

                    modelo.addRow(filas);
                }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error al insertar datos");
        }
    }
    
    private void cargarTablaDeudas(){
        try{
            DefaultTableModel modelo = new DefaultTableModel();
            jTable2.setModel(modelo);
            
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            Connection con = conn.getConexion();
            
            String sql = "SELECT * FROM deuda ORDER BY fecha_carga";
            
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMD = rs.getMetaData();
            int cantidadColumnas = rsMD.getColumnCount();
            
            modelo.addColumn("ID");
            modelo.addColumn("Fecha");
            modelo.addColumn("Descripcion");
            modelo.addColumn("Monto ($)");
            modelo.addColumn("Monto (Bs)");
            modelo.addColumn("Tasa del Dolar (Bs)");
            modelo.addColumn("ID Servicio");
            
            while(rs.next()){
                Object[] filas = new Object[cantidadColumnas];
                
                for(int i=0;i<cantidadColumnas;i++){
                    filas[i] = rs.getObject(i+1);
                }
                
                modelo.addRow(filas);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error al insertar datos");
        }
    }
    
    
    public void llenarCajaTexto(){
        jTextFieldUsuario.setText(nombre+" "+apellido);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new Deuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonInformacion;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonMinimizar;
    private javax.swing.JButton jButtonPerfil;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JComboBox jComboBoxAño;
    private javax.swing.JComboBox jComboBoxMes;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    public javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
