
package Vista;

import static Controlador.Main.apellido;
import static Controlador.Main.frmMenu;
import static Controlador.Main.nombre;
import static Controlador.Main.casas;
import Controlador.Reporte;
import Controlador.Pagos;
import Modelo.Casa;
import Modelo.CasaSQL;
import static Vista.Menu.frmMinimenu;
import static Vista.Menu.frmPerfil;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Documentos extends javax.swing.JFrame {

    Reporte reporte = new Reporte();
    int numero = 0, valor = 0, valor2 = 0;
    
    public Documentos() {
        initComponents();
        setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imágenes/Ícono del Programa.png")).getImage());
        llenarCajaTexto();
        jPanelBalance.setVisible(false);
        jPanelSolvencia.setVisible(false);

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSolvencia = new javax.swing.JPanel();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldEstado = new javax.swing.JTextField();
        jTextFieldCasa = new javax.swing.JTextField();
        jLabelTitulo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelOpcionSolvencia = new javax.swing.JLabel();
        jPanelBalance = new javax.swing.JPanel();
        jComboBoxMes = new javax.swing.JComboBox();
        jComboBoxAño = new javax.swing.JComboBox();
        jLabelOpcionBalance = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonPerfil = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jButtonEmitir = new javax.swing.JButton();
        jButtonMinimizar = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonPropietarios = new javax.swing.JButton();
        jButtonMorosos = new javax.swing.JButton();
        jButtonSolvencias = new javax.swing.JButton();
        jButtonBalance = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSolvencia.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSolvencia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Botones Adicionales/Botón Buscar (Lupa).png"))); // NOI18N
        jButtonBuscar.setBorder(null);
        jButtonBuscar.setContentAreaFilled(false);
        jButtonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jPanelSolvencia.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 20, 40));

        jTextFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.setOpaque(false);
        jPanelSolvencia.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 90, 20));

        jTextFieldApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldApellido.setBorder(null);
        jTextFieldApellido.setOpaque(false);
        jPanelSolvencia.add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 90, 20));

        jTextFieldCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCedula.setBorder(null);
        jTextFieldCedula.setOpaque(false);
        jPanelSolvencia.add(jTextFieldCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 100, 20));

        jTextFieldEstado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEstado.setBorder(null);
        jTextFieldEstado.setOpaque(false);
        jPanelSolvencia.add(jTextFieldEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 90, 20));

        jTextFieldCasa.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCasa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCasa.setBorder(null);
        jTextFieldCasa.setOpaque(false);
        jTextFieldCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCasaActionPerformed(evt);
            }
        });
        jPanelSolvencia.add(jTextFieldCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 60, 20));

        jLabelTitulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto Pequeña (Registro).png"))); // NOI18N
        jPanelSolvencia.add(jLabelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 100, 40));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Casa");
        jPanelSolvencia.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, 20));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);
        jPanelSolvencia.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 20, 20));

        jLabelOpcionSolvencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/4. Documentos/Opcion Solvencia.png"))); // NOI18N
        jPanelSolvencia.add(jLabelOpcionSolvencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 560, -1));

        getContentPane().add(jPanelSolvencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, 180));

        jPanelBalance.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBalance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxMes.setBackground(new java.awt.Color(240, 240, 240));
        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBoxMes.setBorder(null);
        jComboBoxMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMesItemStateChanged(evt);
            }
        });
        jPanelBalance.add(jComboBoxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 120, 20));

        jComboBoxAño.setBackground(new java.awt.Color(240, 240, 240));
        jComboBoxAño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031" }));
        jComboBoxAño.setBorder(null);
        jComboBoxAño.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxAñoItemStateChanged(evt);
            }
        });
        jPanelBalance.add(jComboBoxAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 120, 20));

        jLabelOpcionBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/4. Documentos/Opcion Balance.png"))); // NOI18N
        jPanelBalance.add(jLabelOpcionBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanelBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, 140));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Perfil (Sesión Actual).png"))); // NOI18N
        jButtonPerfil.setBorder(null);
        jButtonPerfil.setBorderPainted(false);
        jButtonPerfil.setContentAreaFilled(false);
        jButtonPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 3, 50, 40));

        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Tablas/Botón Regresar.png"))); // NOI18N
        jButtonRegresar.setBorderPainted(false);
        jButtonRegresar.setContentAreaFilled(false);
        jButtonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Tablas/Botón Regresar (Presionado).png"))); // NOI18N
        jButtonRegresar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Tablas/Botón Regresar (Presionado).png"))); // NOI18N
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 40, 40));

        jButtonEmitir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/4. Documentos/Botón Emitir.png"))); // NOI18N
        jButtonEmitir.setBorder(null);
        jButtonEmitir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEmitir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/4. Documentos/Botón Emitir (Presionado).png"))); // NOI18N
        jButtonEmitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmitirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEmitir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 610, 120, 30));

        jButtonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Minimizar.png"))); // NOI18N
        jButtonMinimizar.setBorder(null);
        jButtonMinimizar.setContentAreaFilled(false);
        jButtonMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 17, 20, 10));

        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Cerrar.png"))); // NOI18N
        jButtonCerrar.setBorder(null);
        jButtonCerrar.setContentAreaFilled(false);
        jButtonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 10, 10, 20));

        jButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Menú.png"))); // NOI18N
        jButtonMenu.setBorder(null);
        jButtonMenu.setContentAreaFilled(false);
        jButtonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, -1, 40, 50));

        jTextFieldUsuario.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUsuario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 180, 30));

        jButtonPropietarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/4. Documentos/Botón Lista de Propietarios.png"))); // NOI18N
        jButtonPropietarios.setBorder(null);
        jButtonPropietarios.setContentAreaFilled(false);
        jButtonPropietarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPropietarios.setRolloverEnabled(false);
        jButtonPropietarios.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/4. Documentos/Botón Lista de Propietarios Presionado.png"))); // NOI18N
        jButtonPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPropietariosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPropietarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 180, 200));

        jButtonMorosos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/4. Documentos/Botón Lista de Morosos.png"))); // NOI18N
        jButtonMorosos.setBorder(null);
        jButtonMorosos.setContentAreaFilled(false);
        jButtonMorosos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMorosos.setRolloverEnabled(false);
        jButtonMorosos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/4. Documentos/Botón Lista de Morosos Presionado.png"))); // NOI18N
        jButtonMorosos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMorososActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMorosos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 180, 200));

        jButtonSolvencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/4. Documentos/Botón Solvencias.png"))); // NOI18N
        jButtonSolvencias.setBorder(null);
        jButtonSolvencias.setContentAreaFilled(false);
        jButtonSolvencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSolvencias.setRolloverEnabled(false);
        jButtonSolvencias.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/4. Documentos/Botón Solvencia Presionado.png"))); // NOI18N
        jButtonSolvencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolvenciasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSolvencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 180, 200));

        jButtonBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/4. Documentos/Botón Balance.png"))); // NOI18N
        jButtonBalance.setBorder(null);
        jButtonBalance.setContentAreaFilled(false);
        jButtonBalance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBalance.setRolloverEnabled(false);
        jButtonBalance.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/4. Documentos/Botón Balance Presionado.png"))); // NOI18N
        jButtonBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBalanceActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, 200));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/4. Documentos/Documentos.png"))); // NOI18N
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizarActionPerformed
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizarActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        this.dispose();
        frmMenu.setVisible(true);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBalanceActionPerformed
        limpiarComboBox();
        
        jButtonMorosos.setSelected(false);
        jButtonPropietarios.setSelected(false);
        jButtonSolvencias.setSelected(false);
        jButtonBalance.setSelected(true);
        jPanelSolvencia.setVisible(false);
        jPanelBalance.setVisible(true);
        
        numero = 1;
    }//GEN-LAST:event_jButtonBalanceActionPerformed

    private void jButtonSolvenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolvenciasActionPerformed
        limpiarCajaSolvencia();
        
        jButtonBalance.setSelected(false);
        jButtonMorosos.setSelected(false);
        jButtonPropietarios.setSelected(false);
        jButtonSolvencias.setSelected(true);
        jPanelBalance.setVisible(false);
        jPanelSolvencia.setVisible(true);
        
        numero = 2;
    }//GEN-LAST:event_jButtonSolvenciasActionPerformed

    private void jButtonMorososActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMorososActionPerformed
        jButtonPropietarios.setSelected(false);
        jButtonSolvencias.setSelected(false);
        jButtonBalance.setSelected(false);
        jButtonMorosos.setSelected(true);
        jPanelBalance.setVisible(false);
        jPanelSolvencia.setVisible(false);
        
        numero = 3;
        valor = 0;
    }//GEN-LAST:event_jButtonMorososActionPerformed

    private void jButtonPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPropietariosActionPerformed
        jButtonSolvencias.setSelected(false);
        jButtonBalance.setSelected(false);
        jButtonMorosos.setSelected(false);
        jButtonPropietarios.setSelected(true);
        jPanelBalance.setVisible(false);
        jPanelSolvencia.setVisible(false);
        
        numero = 4;
        valor = 0;
    }//GEN-LAST:event_jButtonPropietariosActionPerformed

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        frmMinimenu.setVisible(true);
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerfilActionPerformed
        frmPerfil.setVisible(true);
    }//GEN-LAST:event_jButtonPerfilActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        buscarCasa();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonEmitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmitirActionPerformed
        if(numero == 3){actualizar_deudas();}
        reporte.generar(numero,valor,valor2);
    }//GEN-LAST:event_jButtonEmitirActionPerformed

    private void jComboBoxAñoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxAñoItemStateChanged
        if(jComboBoxAño.getSelectedIndex() > 0){
            valor = Integer.valueOf(jComboBoxAño.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jComboBoxAñoItemStateChanged

    private void jComboBoxMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMesItemStateChanged
        if(jComboBoxMes.getSelectedIndex() > 0){
            valor2 = jComboBoxMes.getSelectedIndex();
        }
    }//GEN-LAST:event_jComboBoxMesItemStateChanged

    private void jTextFieldCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCasaActionPerformed

    private void buscarCasa(){
        Casa modeloCasa = new Casa();
        CasaSQL modeloCasaSQL = new CasaSQL();
        
        if(jTextFieldCasa.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo de busqueda vacio. Ingrese "
                    + "el numero de la casa a emitir la solvencia");
        }
        else{
            modeloCasa.setNumero_casa(Integer.parseInt(jTextFieldCasa.getText()));
            
            if(modeloCasa.getNumero_casa() > 0  && modeloCasa.getNumero_casa() < 49){
                if(modeloCasaSQL.buscarCasaSolvente(modeloCasa)){
                    jTextFieldNombre.setText(modeloCasa.getNombre());
                    jTextFieldApellido.setText(modeloCasa.getApellido());
                    jTextFieldCedula.setText(modeloCasa.getCedula_propietario());
                    jTextFieldEstado.setText(modeloCasa.getEstado_pago());
                    valor = modeloCasa.getNumero_casa();
                }
                else{
                    JOptionPane.showMessageDialog(null, "La casa buscada se encuentra"
                            + "morosa, por lo que no se le permite emitir solvencias");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Numero de Casa invalido. "
                        + "Solo existen 48 casas");
            }
        }
    }
    
    private void actualizar_deudas(){
        Pagos pagos = new Pagos();
        
        for(int i=0;i<casas;i++){
            pagos.actualizar_deuda_casa(i+1);
        }
    }
    
    private void limpiarCajaSolvencia(){
        jTextFieldCasa.setText(null);
        jTextFieldNombre.setText(null);
        jTextFieldApellido.setText(null);
        jTextFieldCedula.setText(null);
        jTextFieldEstado.setText(null);
    }
    
    private void limpiarComboBox(){
        jComboBoxMes.setSelectedIndex(0);
        jComboBoxAño.setSelectedIndex(0);
    }
    
    public void llenarCajaTexto(){
        jTextFieldUsuario.setText(nombre+" "+apellido);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Documentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Documentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Documentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Documentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Documentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonBalance;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonEmitir;
    public javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonMinimizar;
    public javax.swing.JButton jButtonMorosos;
    public javax.swing.JButton jButtonPerfil;
    public javax.swing.JButton jButtonPropietarios;
    private javax.swing.JButton jButtonRegresar;
    public javax.swing.JButton jButtonSolvencias;
    private javax.swing.JComboBox jComboBoxAño;
    private javax.swing.JComboBox jComboBoxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelOpcionBalance;
    private javax.swing.JLabel jLabelOpcionSolvencia;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBalance;
    private javax.swing.JPanel jPanelSolvencia;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCasa;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldNombre;
    public javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
