
package Vista;

import Controlador.Pagos;
import Modelo.Pago;
import Modelo.PagoSQL;
import Modelo.DeudaSQL;
import Modelo.DeudaE;
import Modelo.DeudaESQL;
import Modelo.CasaSQL;
import Controlador.Tasa;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class InformacionPago extends javax.swing.JFrame {
    
    //DECLARACION DE OBJETOS PARA LA MODIFICACION DE LA BASE DE DATOS

    //Getters y Setters de atributos (BD)
    Pago modeloPago = new Pago();
    Pago modeloPago_antiguo = new Pago();
    DeudaE modeloDeudaE = new DeudaE();

    //Metodos y consultas para modificar BD
    PagoSQL modeloPagoSQL = new PagoSQL();
    DeudaESQL modeloDeudaESQL = new DeudaESQL();
    DeudaSQL modeloDeudaSQL = new DeudaSQL();
    CasaSQL modeloCasaSQL = new CasaSQL();
    
    //Objeto para la transformacion de dinero mediante la tasa del dolar en el dia
    Tasa tasa = new Tasa();
    Pagos pagos = new Pagos();
    
    public InformacionPago() {
        initComponents();
        setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imágenes/Ícono del Programa.png")).getImage());
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldMonto = new javax.swing.JTextField();
        jTextFieldFecha = new javax.swing.JTextField();
        jTextFieldConcepto = new javax.swing.JTextField();
        jTextFieldCasa = new javax.swing.JTextField();
        jTextFieldBuscar = new javax.swing.JTextField();
        jTextFieldCodigoD = new javax.swing.JTextField();
        jLabelCodigo = new javax.swing.JLabel();
        jLabelMonto = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jLabelCodigoD = new javax.swing.JLabel();
        jLabelCasa = new javax.swing.JLabel();
        jLabelBuscar = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jComboBoxMoneda = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldCodigo.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldCodigo.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldCodigo.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldCodigo.setText("Campo Único");
        jTextFieldCodigo.setBorder(null);
        jTextFieldCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCodigoMouseClicked(evt);
            }
        });
        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 130, 20));

        jTextFieldMonto.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldMonto.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldMonto.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldMonto.setBorder(null);
        jTextFieldMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMontoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 195, 130, 20));

        jTextFieldFecha.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldFecha.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldFecha.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldFecha.setText("Año-Mes-Día");
        jTextFieldFecha.setBorder(null);
        jTextFieldFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldFechaMouseClicked(evt);
            }
        });
        jTextFieldFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 295, 130, 20));

        jTextFieldConcepto.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldConcepto.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldConcepto.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldConcepto.setBorder(null);
        jTextFieldConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConceptoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 345, 130, 20));

        jTextFieldCasa.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldCasa.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldCasa.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldCasa.setBorder(null);
        jTextFieldCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCasaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 60, 20));

        jTextFieldBuscar.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldBuscar.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldBuscar.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldBuscar.setText("Buscar");
        jTextFieldBuscar.setBorder(null);
        jTextFieldBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBuscarMouseClicked(evt);
            }
        });
        jTextFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 145, 130, 20));

        jTextFieldCodigoD.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldCodigoD.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldCodigoD.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldCodigoD.setText("Deuda a pagar");
        jTextFieldCodigoD.setBorder(null);
        jTextFieldCodigoD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCodigoDMouseClicked(evt);
            }
        });
        jTextFieldCodigoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoDActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCodigoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 395, 130, 20));

        jLabelCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 150, 40));

        jLabelMonto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 150, 30));

        jLabelFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 150, 30));

        jLabelHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 150, 30));

        jLabelCodigoD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelCodigoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 150, 30));

        jLabelCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto Pequeña (Registro).png"))); // NOI18N
        jPanel1.add(jLabelCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 80, 40));

        jLabelBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 150, 30));

        jButtonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Botones Adicionales/Botón Registrar.png"))); // NOI18N
        jButtonRegistrar.setBorder(null);
        jButtonRegistrar.setContentAreaFilled(false);
        jButtonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 140, 40));

        jButtonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Botones Adicionales/Botón Modificar.png"))); // NOI18N
        jButtonModificar.setBorder(null);
        jButtonModificar.setContentAreaFilled(false);
        jButtonModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 140, 40));

        jButtonBuscar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Botones Adicionales/Botón Buscar (Lupa).png"))); // NOI18N
        jButtonBuscar.setBorder(null);
        jButtonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 30, 30));

        jButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Botones Adicionales/Botón Limpiar.png"))); // NOI18N
        jButtonLimpiar.setBorder(null);
        jButtonLimpiar.setContentAreaFilled(false);
        jButtonLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 140, 40));

        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Cerrar.png"))); // NOI18N
        jButtonCerrar.setBorder(null);
        jButtonCerrar.setContentAreaFilled(false);
        jButtonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 10, 20));

        jComboBoxMoneda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Dólares", "Bolívares" }));
        jComboBoxMoneda.setBorder(null);
        jPanel1.add(jComboBoxMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 150, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 150, 20));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Información Pago Nueva.png"))); // NOI18N
        jLabelFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMontoActionPerformed

    private void jTextFieldFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaActionPerformed

    private void jTextFieldConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConceptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConceptoActionPerformed

    private void jTextFieldCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCasaActionPerformed

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTextFieldCodigoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoDActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        registrar(1);
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        registrar(2);
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jTextFieldBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBuscarMouseClicked
        jTextFieldBuscar.setText(null);
    }//GEN-LAST:event_jTextFieldBuscarMouseClicked

    private void jTextFieldCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCodigoMouseClicked
        jTextFieldCodigo.setText(null);
    }//GEN-LAST:event_jTextFieldCodigoMouseClicked

    private void jTextFieldFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldFechaMouseClicked
        jTextFieldFecha.setText(null);
    }//GEN-LAST:event_jTextFieldFechaMouseClicked

    private void jTextFieldCodigoDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCodigoDMouseClicked
        jTextFieldCodigoD.setText(null);
    }//GEN-LAST:event_jTextFieldCodigoDMouseClicked

    public void registrar(int eleccion){
        //Metodo para Registar (Pasar 1) y Modificar (pasar 2)
        String id = jTextFieldCodigoD.getText();
        int casa = Integer.parseInt(jTextFieldCasa.getText());
        
        //VALIDACION DE CAMPOS VACIOS
        if(jTextFieldCodigo.equals("") || jTextFieldMonto.equals("") || jTextFieldFecha.equals("") ||
            jTextFieldConcepto.equals("") || jTextFieldCodigoD.equals("") || jTextFieldCasa.equals("")
                || jComboBoxMoneda.getSelectedItem().toString().equals("Seleccione")){
            JOptionPane.showMessageDialog(null,"Hay campos vacíos. Llene los todos los campos");
        }
        else{
            //Registrar
            
            
            if(eleccion == 1){
                if(modeloPagoSQL.verificarExistencia(jTextFieldCodigo.getText()) == 0){
                    if(modeloDeudaSQL.verificarExistencia(jTextFieldCodigoD.getText()) == 1){
                        if(!modeloDeudaESQL.saber_deuda_pagada(id,casa)){
                            modeloPago = extraerInformacion_pago();
                            extraerInformacion_restante();

                            pagos.pagar(eleccion,0,modeloPago,modeloPago_antiguo,modeloDeudaE);
                        }
                        else{
                            JOptionPane.showMessageDialog(null,"La deuda que desea "
                                    + "cubrir ha sido pagada con anterioridad en la"
                                    + "casa ingresada");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"No existe una deuda con "
                                + "el codigo que usted ingreso. Intente nuevamente");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Ya existe un pago con el "
                            + "codigo que usted ingreso. Intente nuevamente");
                }
            }
            //Modificar
            else{
                modeloPago = extraerInformacion_pago();
                extraerInformacion_restante();
                pagos.pagar(eleccion,0,modeloPago,modeloPago_antiguo,modeloDeudaE);
            }
        }
        limpiar();
    }
    
    private Pago extraerInformacion_pago(){
        Pago modelo = new Pago();
        
        modelo.setId_pago(jTextFieldCodigo.getText());
        modelo.setFecha_pago(jTextFieldFecha.getText());
        modelo.setDescripcion(jTextFieldConcepto.getText());
        modelo.setId_deuda2(jTextFieldCodigoD.getText());
        modelo.setNumero_casa2(Integer.parseInt(jTextFieldCasa.getText()));
               
        String moneda = jComboBoxMoneda.getSelectedItem().toString();

        if(moneda.equals("Dólares")){
            modelo.setMonto_dolares(Float.parseFloat(jTextFieldMonto.getText()));
            modelo.setMonto_bolivares(0);
        }
        if(moneda.equals("Bolívares")){
            modelo.setMonto_bolivares(Integer.parseInt(jTextFieldMonto.getText()));
            modelo.setMonto_dolares(0);
        }
        
        return modelo;
    }
    
    private void extraerInformacion_restante(){

        modeloDeudaE.setId_deuda2(jTextFieldCodigoD.getText());
        modeloDeudaE.setNumero_casa3(Integer.parseInt(jTextFieldCasa.getText()));
        
        String moneda = jComboBoxMoneda.getSelectedItem().toString();

        if(moneda.equals("Dólares")){
            modeloDeudaE.setMonto_dolares(Float.parseFloat(jTextFieldMonto.getText()));
            modeloDeudaE.setMonto_bolivares(0);
        }
        if(moneda.equals("Bolívares")){
            modeloDeudaE.setMonto_bolivares(Integer.parseInt(jTextFieldMonto.getText()));
            modeloDeudaE.setMonto_dolares(0);
        }
    }
    
    private void buscar(){
        //Metodo para buscar y mostrar en pantalla los datos del pago realizado
        modeloPago.setId_pago(jTextFieldBuscar.getText());
        
        if(modeloPagoSQL.buscar(modeloPago)){
            jTextFieldCodigo.setText(modeloPago.getId_pago());
            
            if(modeloPago.getMonto_dolares() > 0){
                jTextFieldMonto.setText(String.valueOf(modeloPago.getMonto_dolares()));
                jComboBoxMoneda.setSelectedIndex(1);
            }
            if(modeloPago.getMonto_bolivares() > 0){
                jTextFieldMonto.setText(String.valueOf(modeloPago.getMonto_bolivares()));
                jComboBoxMoneda.setSelectedIndex(2);
            }
          
            jTextFieldFecha.setText(modeloPago.getFecha_pago());
            jTextFieldConcepto.setText(modeloPago.getDescripcion());
            jTextFieldCodigoD.setText(modeloPago.getId_deuda2());
            jTextFieldCasa.setText(String.valueOf(modeloPago.getNumero_casa2()));
            
            modeloPago_antiguo = extraerInformacion_pago();
        }
        else{
            JOptionPane.showMessageDialog(null,"Pago no encontrado");
        }
    }
    
    private void limpiar(){
        //Metodo para limpiar los TextField de la vista
        jTextFieldCodigo.setText("Campo Único");
        jTextFieldMonto.setText(null);
        jComboBoxMoneda.setSelectedIndex(0);
        jTextFieldFecha.setText("Año-Mes-Dia");
        jTextFieldConcepto.setText(null);
        jTextFieldCodigoD.setText("Deuda a pagar");
        jTextFieldCasa.setText(null);
        jTextFieldBuscar.setText(null);
        jTextFieldBuscar.setText("Buscar");
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonBuscar;
    public javax.swing.JButton jButtonCerrar;
    public javax.swing.JButton jButtonLimpiar;
    public javax.swing.JButton jButtonModificar;
    public javax.swing.JButton jButtonRegistrar;
    public javax.swing.JComboBox jComboBoxMoneda;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabelBuscar;
    public javax.swing.JLabel jLabelCasa;
    public javax.swing.JLabel jLabelCodigo;
    public javax.swing.JLabel jLabelCodigoD;
    public javax.swing.JLabel jLabelFecha;
    public javax.swing.JLabel jLabelFondo;
    public javax.swing.JLabel jLabelHora;
    public javax.swing.JLabel jLabelMonto;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextFieldBuscar;
    public javax.swing.JTextField jTextFieldCasa;
    public javax.swing.JTextField jTextFieldCodigo;
    public javax.swing.JTextField jTextFieldCodigoD;
    public javax.swing.JTextField jTextFieldConcepto;
    public javax.swing.JTextField jTextFieldFecha;
    public javax.swing.JTextField jTextFieldMonto;
    // End of variables declaration//GEN-END:variables
}
