
package Vista;

import Modelo.Casa;
import Modelo.CasaSQL;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class InformacionPropietarios extends javax.swing.JFrame {

    Casa modCasa = new Casa();
    CasaSQL modCasaSQL = new CasaSQL();
    
    public InformacionPropietarios() {
        initComponents();
        setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imágenes/Ícono del Programa.png")).getImage());
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldCasa = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldEstado = new javax.swing.JTextField();
        jTextFieldBuscar = new javax.swing.JTextField();
        jLabelCasa = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelBuscar = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldCasa.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldCasa.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldCasa.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldCasa.setText("C. Único");
        jTextFieldCasa.setBorder(null);
        jTextFieldCasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCasaMouseClicked(evt);
            }
        });
        jTextFieldCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCasaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 60, 20));

        jTextFieldNombre.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldNombre.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 195, 130, 20));

        jTextFieldApellido.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldApellido.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldApellido.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldApellido.setBorder(null);
        jTextFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 245, 130, 20));

        jTextFieldCedula.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldCedula.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldCedula.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldCedula.setBorder(null);
        jTextFieldCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 295, 130, 20));

        jTextFieldTelefono.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldTelefono.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldTelefono.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldTelefono.setBorder(null);
        jTextFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 345, 130, 20));

        jTextFieldEstado.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldEstado.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldEstado.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldEstado.setText("No modificable");
        jTextFieldEstado.setBorder(null);
        jTextFieldEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldEstadoMouseClicked(evt);
            }
        });
        jTextFieldEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 395, 130, 20));

        jTextFieldBuscar.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldBuscar.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldBuscar.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldBuscar.setText("Buscar");
        jTextFieldBuscar.setBorder(null);
        jTextFieldBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBuscarMouseClicked(evt);
            }
        });
        jTextFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 145, 130, 20));

        jLabelCasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto Pequeña (Registro).png"))); // NOI18N
        jPanel1.add(jLabelCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 80, 40));

        jLabelNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 150, 50));

        jLabelApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 150, 30));

        jLabelCedula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 150, 30));

        jLabelTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 150, 30));

        jLabelEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 150, 30));

        jLabelBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 150, 30));

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Botones Adicionales/Botón Buscar (Lupa).png"))); // NOI18N
        jButtonBuscar.setBorder(null);
        jButtonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 30, 30));

        jButtonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Botones Adicionales/Botón Modificar.png"))); // NOI18N
        jButtonModificar.setBorder(null);
        jButtonModificar.setContentAreaFilled(false);
        jButtonModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 140, 40));

        jButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Botones Adicionales/Botón Limpiar.png"))); // NOI18N
        jButtonLimpiar.setBorder(null);
        jButtonLimpiar.setContentAreaFilled(false);
        jButtonLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 140, 40));

        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Cerrar.png"))); // NOI18N
        jButtonCerrar.setBorder(null);
        jButtonCerrar.setContentAreaFilled(false);
        jButtonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 10, 20));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Información de Propietario.png"))); // NOI18N
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCasaActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoActionPerformed

    private void jTextFieldCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaActionPerformed

    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoActionPerformed

    private void jTextFieldEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstadoActionPerformed

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        setVisible(false);
        limpiar();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        modificar();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jTextFieldBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBuscarMouseClicked
        jTextFieldBuscar.setText(null);
    }//GEN-LAST:event_jTextFieldBuscarMouseClicked

    private void jTextFieldCasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCasaMouseClicked
        jTextFieldCasa.setText(null);
    }//GEN-LAST:event_jTextFieldCasaMouseClicked

    private void jTextFieldEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldEstadoMouseClicked
        jTextFieldEstado.setText(null);
    }//GEN-LAST:event_jTextFieldEstadoMouseClicked
    
    private void buscar(){
        if(jTextFieldBuscar.equals("")){
            JOptionPane.showMessageDialog(null,"Campo vacío. Ingrese la casa de la informacion a buscar");
        }
        else{
            modCasa.setNumero_casa(Integer.parseInt(jTextFieldBuscar.getText()));

            if(modCasaSQL.buscar(modCasa)){
               jTextFieldCasa.setText(String.valueOf(modCasa.getNumero_casa()));
               jTextFieldNombre.setText(modCasa.getNombre());
               jTextFieldApellido.setText(modCasa.getApellido());
               jTextFieldCedula.setText(modCasa.getCedula_propietario());
               jTextFieldTelefono.setText(String.valueOf(modCasa.getTelefono()));
               jTextFieldEstado.setText(modCasa.getEstado_pago());
            }
            else{
               JOptionPane.showMessageDialog(null,"Propietario no encontrado");         
            }
        }
    }
    
    private void modificar(){
        if(jTextFieldCasa.equals("") || jTextFieldNombre.equals("") || jTextFieldApellido.equals("") ||
            jTextFieldTelefono.equals("") || jTextFieldCedula.equals("")){
            JOptionPane.showMessageDialog(null,"Hay campos vacíos. Busque la casa a modificar");
        }
        else{
            modCasa.setCedula_propietario(jTextFieldCedula.getText());
            modCasa.setNombre(jTextFieldNombre.getText());
            modCasa.setApellido(jTextFieldApellido.getText());
            modCasa.setTelefono(jTextFieldTelefono.getText());
            modCasa.setNumero_casa(Integer.parseInt(jTextFieldCasa.getText()));


            if(modCasaSQL.modificar(modCasa)){
               JOptionPane.showMessageDialog(null,"Datos modificados exitosamente"); 
            }
            else{
               JOptionPane.showMessageDialog(null,"Error al modificar");         
            }
            limpiar();
        } 
    }
    
    private void limpiar(){
        jTextFieldCasa.setText("C. Único");
        jTextFieldCedula.setText(null);
        jTextFieldNombre.setText(null);
        jTextFieldApellido.setText(null);
        jTextFieldTelefono.setText(null);
        jTextFieldEstado.setText("No modificable");
        jTextFieldBuscar.setText("Buscar");
    }
    /**
     * @param args the command line arguments
     */
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionPropietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionPropietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionPropietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionPropietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionPropietarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonBuscar;
    public javax.swing.JButton jButtonCerrar;
    public javax.swing.JButton jButtonLimpiar;
    public javax.swing.JButton jButtonModificar;
    public javax.swing.JLabel jLabelApellido;
    public javax.swing.JLabel jLabelBuscar;
    public javax.swing.JLabel jLabelCasa;
    public javax.swing.JLabel jLabelCedula;
    public javax.swing.JLabel jLabelEstado;
    public javax.swing.JLabel jLabelFondo;
    public javax.swing.JLabel jLabelNombre;
    public javax.swing.JLabel jLabelTelefono;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextFieldApellido;
    public javax.swing.JTextField jTextFieldBuscar;
    public javax.swing.JTextField jTextFieldCasa;
    public javax.swing.JTextField jTextFieldCedula;
    public javax.swing.JTextField jTextFieldEstado;
    public javax.swing.JTextField jTextFieldNombre;
    public javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
