
package Vista;

import Controlador.Inicializacion;
import static Controlador.Main.frmMenu;
import Modelo.Administrador;
import Modelo.AdministradorSQL;
import Modelo.BalanceSQL;
import java.awt.Image;
import java.awt.Toolkit;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author ARANAGA
 */
public class Login extends javax.swing.JFrame {

    public static RegistroUsuario frmRegistroUsuario;
    public static RecuperarContraseña frmRecuperarContraseña;

    Administrador modelo = new Administrador();
    AdministradorSQL modeloSQL = new AdministradorSQL();
    
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelCajaTexto1 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelCajaTexto2 = new javax.swing.JLabel();
        jButtonIngresar = new javax.swing.JButton();
        jButtonCrearCuenta = new javax.swing.JButton();
        jButtonContraseñaOlvidada = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jButtonMinimizar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setName("Login"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldUsuario.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldUsuario.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 200, 20));

        jLabelCajaTexto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Caja de Texto.png"))); // NOI18N
        jPanel1.add(jLabelCajaTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        jPasswordField.setBackground(new java.awt.Color(240, 240, 240));
        jPasswordField.setBorder(null);
        jPasswordField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 190, 20));

        jLabelCajaTexto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Caja de Texto.png"))); // NOI18N
        jPanel1.add(jLabelCajaTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, -1, 40));

        jButtonIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Ingresar.png"))); // NOI18N
        jButtonIngresar.setBorder(null);
        jButtonIngresar.setContentAreaFilled(false);
        jButtonIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonIngresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Ingresar (Presionado).png"))); // NOI18N
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 160, 50));

        jButtonCrearCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Crear Cuenta.png"))); // NOI18N
        jButtonCrearCuenta.setBorder(null);
        jButtonCrearCuenta.setContentAreaFilled(false);
        jButtonCrearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCrearCuenta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Crear Cuenta (Seleccionado).png"))); // NOI18N
        jButtonCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 80, 20));

        jButtonContraseñaOlvidada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Olvidó Contraseña.png"))); // NOI18N
        jButtonContraseñaOlvidada.setBorder(null);
        jButtonContraseñaOlvidada.setContentAreaFilled(false);
        jButtonContraseñaOlvidada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonContraseñaOlvidada.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Olvidó Contraseña (Seleccionado).png"))); // NOI18N
        jButtonContraseñaOlvidada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContraseñaOlvidadaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonContraseñaOlvidada, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 120, 20));

        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Cerrar.png"))); // NOI18N
        jButtonCerrar.setBorder(null);
        jButtonCerrar.setContentAreaFilled(false);
        jButtonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 10, 10, 20));

        jButtonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Minimizar.png"))); // NOI18N
        jButtonMinimizar.setBorder(null);
        jButtonMinimizar.setContentAreaFilled(false);
        jButtonMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 17, 20, 10));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Iniciar Sesión.png"))); // NOI18N
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        ingresar();
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jButtonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearCuentaActionPerformed
        frmRegistroUsuario = new RegistroUsuario();
        frmRegistroUsuario.setVisible(true);
    }//GEN-LAST:event_jButtonCrearCuentaActionPerformed

    private void jButtonContraseñaOlvidadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContraseñaOlvidadaActionPerformed
        frmRecuperarContraseña = new RecuperarContraseña();
        frmRecuperarContraseña.setVisible(true);
    }//GEN-LAST:event_jButtonContraseñaOlvidadaActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizarActionPerformed
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizarActionPerformed
    
    private void ingresar(){
        Inicializacion iniciar = new Inicializacion();
        BalanceSQL balance = new BalanceSQL();
        LocalDateTime fecha = LocalDateTime.now();
        int año = 0, mes = 0;
        
        String contraseña = new String(jPasswordField.getPassword());
        
        try{
            if(!jTextFieldUsuario.getText().equals("") && !contraseña.equals("")){
                modelo.setNombre_usuario(jTextFieldUsuario.getText());
                modelo.setContraseña(contraseña);

                if(modeloSQL.login(modelo)){
                    iniciar.inicializarDatosUsuario(modelo);
                    
                    año = fecha.getYear();
                    mes = fecha.getMonthValue();
            
                    if(!balance.comprobarExistencia(año,mes)){
                        if(iniciar.inicializacionContable(año,mes)){
                            JOptionPane.showMessageDialog(null, "Balance y Resumen General del mes: Inicializado");
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Balance y Resumen General del mes: Error de carga");
                        }
                    }
                    
                    this.dispose();

                    frmMenu = new Menu();
                    frmMenu.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(null,"Datos Incorrectos");
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"Debe ingresar sus datos");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error en boton: "+e.getMessage());
        }
    }
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imágenes/Ícono del Programa.png"));
        return retValue;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonCerrar;
    public javax.swing.JButton jButtonContraseñaOlvidada;
    public javax.swing.JButton jButtonCrearCuenta;
    public javax.swing.JButton jButtonIngresar;
    public javax.swing.JButton jButtonMinimizar;
    public javax.swing.JLabel jLabelCajaTexto1;
    public javax.swing.JLabel jLabelCajaTexto2;
    public javax.swing.JLabel jLabelFondo;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPasswordField jPasswordField;
    public javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
