
package Vista;

import static Controlador.Main.nombre;
import static Controlador.Main.apellido;
import static Controlador.Main.ultimaentrada;
import static Controlador.Main.cierreBalance;
import javax.swing.ImageIcon;


public class Menu extends javax.swing.JFrame {
    
    public static Minimenu frmMinimenu;
    public static PerfilUsuario frmPerfil;
    boolean titulo_cambiado = false;  
    
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imágenes/Ícono del Programa.png")).getImage());
        llenarCajaTexto();
        frmMinimenu = new Minimenu();
        frmPerfil = new PerfilUsuario();
        jLabelMenu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSolvencias = new javax.swing.JButton();
        jButtonMinimizar = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jButtonFacturas = new javax.swing.JButton();
        jButtonPagos = new javax.swing.JButton();
        jButtonServicios = new javax.swing.JButton();
        jButtonBalance = new javax.swing.JButton();
        jButtonHabitantes = new javax.swing.JButton();
        jButtonDeudaGeneral = new javax.swing.JButton();
        jButtonDeudaDetallada = new javax.swing.JButton();
        jButtonPerfil = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jLabelMenu = new javax.swing.JLabel();
        jTextFieldUsuarioBienvenida = new javax.swing.JTextField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelBienvenida = new javax.swing.JLabel();
        jLabelModificacion = new javax.swing.JLabel();
        jLabelEntrada = new javax.swing.JLabel();
        jTextFieldCierreBalance = new javax.swing.JTextField();
        jTextFieldUltimaEntrada = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Menu"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSolvencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Documentos.png"))); // NOI18N
        jButtonSolvencias.setBorder(null);
        jButtonSolvencias.setContentAreaFilled(false);
        jButtonSolvencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSolvencias.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Documentos (Seleccionado).png"))); // NOI18N
        jButtonSolvencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolvenciasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSolvencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 180, 200));

        jButtonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Minimizar.png"))); // NOI18N
        jButtonMinimizar.setBorder(null);
        jButtonMinimizar.setContentAreaFilled(false);
        jButtonMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 17, 20, 10));

        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Cerrar.png"))); // NOI18N
        jButtonCerrar.setBorder(null);
        jButtonCerrar.setContentAreaFilled(false);
        jButtonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 10, 10, 20));

        jButtonFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Facturas.png"))); // NOI18N
        jButtonFacturas.setBorder(null);
        jButtonFacturas.setContentAreaFilled(false);
        jButtonFacturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFacturas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Facturas (Seleccionado).png"))); // NOI18N
        jButtonFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFacturasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 180, 200));

        jButtonPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Pagos.png"))); // NOI18N
        jButtonPagos.setBorder(null);
        jButtonPagos.setContentAreaFilled(false);
        jButtonPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPagos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Pagos (Seleccionado).png"))); // NOI18N
        jButtonPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 180, 200));

        jButtonServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Servicios.png"))); // NOI18N
        jButtonServicios.setBorder(null);
        jButtonServicios.setContentAreaFilled(false);
        jButtonServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonServicios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Servicios (Seleccionado).png"))); // NOI18N
        jButtonServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonServiciosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 180, 200));

        jButtonBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Balance General.png"))); // NOI18N
        jButtonBalance.setBorder(null);
        jButtonBalance.setContentAreaFilled(false);
        jButtonBalance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBalance.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Balance General (Seleccionado).png"))); // NOI18N
        jButtonBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBalanceActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 180, 200));

        jButtonHabitantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Propietarios.png"))); // NOI18N
        jButtonHabitantes.setBorder(null);
        jButtonHabitantes.setContentAreaFilled(false);
        jButtonHabitantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHabitantes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Propietarios (Seleccionado).png"))); // NOI18N
        jButtonHabitantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitantesActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHabitantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 180, 200));

        jButtonDeudaGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Deuda General.png"))); // NOI18N
        jButtonDeudaGeneral.setBorder(null);
        jButtonDeudaGeneral.setContentAreaFilled(false);
        jButtonDeudaGeneral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeudaGeneral.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Deuda General (Seleccionado).png"))); // NOI18N
        jButtonDeudaGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeudaGeneralActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDeudaGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 180, 200));

        jButtonDeudaDetallada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Deuda Detallada.png"))); // NOI18N
        jButtonDeudaDetallada.setBorder(null);
        jButtonDeudaDetallada.setContentAreaFilled(false);
        jButtonDeudaDetallada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeudaDetallada.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Deuda Detallada (Seleccionado).png"))); // NOI18N
        jButtonDeudaDetallada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeudaDetalladaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDeudaDetallada, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 180, 200));

        jButtonPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Perfil (Sesión Actual).png"))); // NOI18N
        jButtonPerfil.setBorder(null);
        jButtonPerfil.setBorderPainted(false);
        jButtonPerfil.setContentAreaFilled(false);
        jButtonPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 3, 50, 40));

        jButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Botones/Botón Menú.png"))); // NOI18N
        jButtonMenu.setBorder(null);
        jButtonMenu.setContentAreaFilled(false);
        jButtonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, -1, 40, 50));

        jLabelMenu.setFont(new java.awt.Font("Microsoft JhengHei", 0, 30)); // NOI18N
        jLabelMenu.setForeground(new java.awt.Color(153, 153, 153));
        jLabelMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu.setText("Menú Principal");
        jLabelMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 360, 60));

        jTextFieldUsuarioBienvenida.setFont(new java.awt.Font("Microsoft JhengHei", 0, 30)); // NOI18N
        jTextFieldUsuarioBienvenida.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUsuarioBienvenida.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldUsuarioBienvenida.setBorder(null);
        jTextFieldUsuarioBienvenida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextFieldUsuarioBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 180, 40));

        jTextFieldUsuario.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUsuario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 180, 30));

        jLabelBienvenida.setFont(new java.awt.Font("Microsoft JhengHei", 0, 30)); // NOI18N
        jLabelBienvenida.setForeground(new java.awt.Color(153, 153, 153));
        jLabelBienvenida.setText("¡Bienvenido,");
        jLabelBienvenida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabelBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 220, 40));

        jLabelModificacion.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 15)); // NOI18N
        jLabelModificacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelModificacion.setText("Próximo cierre de balance:");
        jPanel1.add(jLabelModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 680, -1, 30));

        jLabelEntrada.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 15)); // NOI18N
        jLabelEntrada.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEntrada.setText("Última Entrada:");
        jPanel1.add(jLabelEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 680, -1, 30));

        jTextFieldCierreBalance.setBackground(new java.awt.Color(11, 170, 88));
        jTextFieldCierreBalance.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jTextFieldCierreBalance.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCierreBalance.setBorder(null);
        jTextFieldCierreBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCierreBalanceActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCierreBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 680, 70, 30));

        jTextFieldUltimaEntrada.setBackground(new java.awt.Color(11, 170, 88));
        jTextFieldUltimaEntrada.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jTextFieldUltimaEntrada.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUltimaEntrada.setBorder(null);
        jTextFieldUltimaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUltimaEntradaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldUltimaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 680, 100, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/2. Menú/Menú.png"))); // NOI18N
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBalanceActionPerformed
        BalanceGeneral frmBalanceGeneral = new BalanceGeneral();
        this.setVisible(false);
        frmBalanceGeneral.setVisible(true);
        cambiarTitulo();
    }//GEN-LAST:event_jButtonBalanceActionPerformed

    private void jButtonHabitantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitantesActionPerformed
        Propietarios frmHabitantes = new Propietarios();
        this.setVisible(false);
        frmHabitantes.setVisible(true);
        cambiarTitulo();
    }//GEN-LAST:event_jButtonHabitantesActionPerformed

    private void jButtonPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagosActionPerformed
        Pagos frmPagos = new Pagos();
        this.setVisible(false);
        frmPagos.setVisible(true);
        cambiarTitulo();
    }//GEN-LAST:event_jButtonPagosActionPerformed

    private void jButtonServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServiciosActionPerformed
        Servicio frmServicios = new Servicio();
        this.setVisible(false);
        frmServicios.setVisible(true);
        cambiarTitulo();
    }//GEN-LAST:event_jButtonServiciosActionPerformed

    private void jButtonDeudaGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeudaGeneralActionPerformed
        Deuda frmDeudas = new Deuda();
        this.setVisible(false);
        frmDeudas.setVisible(true);
        cambiarTitulo();
    }//GEN-LAST:event_jButtonDeudaGeneralActionPerformed

    private void jButtonDeudaDetalladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeudaDetalladaActionPerformed
        DeudaDetalladas frmDeudaDetallada = new DeudaDetalladas();
        this.setVisible(false);
        frmDeudaDetallada.setVisible(true);
        cambiarTitulo();
    }//GEN-LAST:event_jButtonDeudaDetalladaActionPerformed

    private void jButtonSolvenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolvenciasActionPerformed
        Documentos frmSolvencias = new Documentos();
        this.setVisible(false);
        frmSolvencias.setVisible(true);
        cambiarTitulo();
    }//GEN-LAST:event_jButtonSolvenciasActionPerformed

    private void jButtonFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFacturasActionPerformed
        Factura frmFacturas = new Factura();
        this.setVisible(false);
        frmFacturas.setVisible(true);
        cambiarTitulo();
    }//GEN-LAST:event_jButtonFacturasActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizarActionPerformed
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizarActionPerformed

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        frmMinimenu.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerfilActionPerformed
        frmPerfil.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jButtonPerfilActionPerformed

    private void jTextFieldUltimaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUltimaEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUltimaEntradaActionPerformed

    private void jTextFieldCierreBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCierreBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCierreBalanceActionPerformed
    
    private void cambiarTitulo(){
        if(!titulo_cambiado){
            jLabelBienvenida.setVisible(false);
            jTextFieldUsuarioBienvenida.setVisible(false);
            jLabelMenu.setVisible(true);
            titulo_cambiado = true;
        }
    }
    
    public void llenarCajaTexto(){
        jTextFieldUsuario.setText(nombre+" "+apellido);
        jTextFieldUsuarioBienvenida.setText(nombre+"!");
        jTextFieldUltimaEntrada.setText(ultimaentrada);
        jTextFieldCierreBalance.setText(cierreBalance);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonBalance;
    public javax.swing.JButton jButtonCerrar;
    public javax.swing.JButton jButtonDeudaDetallada;
    public javax.swing.JButton jButtonDeudaGeneral;
    public javax.swing.JButton jButtonFacturas;
    public javax.swing.JButton jButtonHabitantes;
    public javax.swing.JButton jButtonMenu;
    public javax.swing.JButton jButtonMinimizar;
    public javax.swing.JButton jButtonPagos;
    public javax.swing.JButton jButtonPerfil;
    public javax.swing.JButton jButtonServicios;
    public javax.swing.JButton jButtonSolvencias;
    private javax.swing.JLabel jLabelBienvenida;
    private javax.swing.JLabel jLabelEntrada;
    public javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelModificacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCierreBalance;
    private javax.swing.JTextField jTextFieldUltimaEntrada;
    public javax.swing.JTextField jTextFieldUsuario;
    public javax.swing.JTextField jTextFieldUsuarioBienvenida;
    // End of variables declaration//GEN-END:variables
}
