
package Vista;

import java.awt.Color;
import javax.swing.ImageIcon;
import Modelo.AdministradorSQL;
import static Controlador.Main.frmLogin;
import static Controlador.Main.frmMenu;
import static Controlador.Main.nombre_usuario;
import static Controlador.Main.nombre;
import static Controlador.Main.apellido;
import static Controlador.Main.ultimaentrada;

/**
 *
 * @author ARANAGA
 */
public class Minimenu extends javax.swing.JFrame {
    
    RespaldoR frmRespaldo = new RespaldoR();
    Creadores frmCreadores = new Creadores();
    AdministradorSQL modeloSQL = new AdministradorSQL();
    
    public Minimenu() {
        initComponents();
        setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imágenes/Ícono del Programa.png")).getImage());
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonRespaldo = new javax.swing.JButton();
        jButtonCerrarsesion = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jButtonAcercade = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRespaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Minimenu/Botón Respaldo y Restauración.png"))); // NOI18N
        jButtonRespaldo.setBorder(null);
        jButtonRespaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRespaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRespaldoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRespaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 210, 50));

        jButtonCerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Minimenu/Cerrar Sesión.png"))); // NOI18N
        jButtonCerrarsesion.setBorder(null);
        jButtonCerrarsesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarsesionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, 50));

        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Cerrar.png"))); // NOI18N
        jButtonCerrar.setBorder(null);
        jButtonCerrar.setContentAreaFilled(false);
        jButtonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 10, 20));

        jButtonAcercade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Minimenu/Acerca de.png"))); // NOI18N
        jButtonAcercade.setBorder(null);
        jButtonAcercade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcercadeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAcercade, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 200, 50));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Minimenu/Minimenu (3 Filas).png"))); // NOI18N
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        frmMenu.setEnabled(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcercadeActionPerformed
        frmCreadores.setVisible(true);
    }//GEN-LAST:event_jButtonAcercadeActionPerformed

    private void jButtonRespaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRespaldoActionPerformed
        frmRespaldo.setVisible(true);
    }//GEN-LAST:event_jButtonRespaldoActionPerformed

    private void jButtonCerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarsesionActionPerformed
        cerrarSesion();
    }//GEN-LAST:event_jButtonCerrarsesionActionPerformed
    
    private void cerrarSesion(){
        boolean activo = true, inactivo;
        
        //Si cambio el estado de sesion del usuario, devolvera true
        inactivo = modeloSQL.estadoSesion(nombre_usuario,activo);
        
        if(inactivo == true){
            cerrarVentanas();
            limpiarVariables();
        }
    }
    
    private void cerrarVentanas(){
        this.dispose(); //Eliminar Frame de Minimenu
        frmMenu.dispose(); //Eliminar Frame de Menu
        frmLogin = new Login();
        frmLogin.setVisible(true); //Mostrar pantalla inicial
    }
    
    private void limpiarVariables(){
        nombre_usuario = "";
        nombre = "";
        apellido = "";
        ultimaentrada = "";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Minimenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Minimenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Minimenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Minimenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Minimenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcercade;
    public javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonCerrarsesion;
    private javax.swing.JButton jButtonRespaldo;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
