
package Vista;

import Modelo.Administrador;
import Modelo.AdministradorSQL;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ARANAGA
 */
public class RecuperarContraseña extends javax.swing.JFrame {

    Administrador modelo = new Administrador();
    AdministradorSQL modeloSQL = new AdministradorSQL();
    
    
    public RecuperarContraseña() {
        initComponents();
        setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imágenes/Ícono del Programa.png")).getImage());
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldR1 = new javax.swing.JTextField();
        jTextFieldP1 = new javax.swing.JTextField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldP2 = new javax.swing.JTextField();
        jTextFieldR2 = new javax.swing.JTextField();
        jTextFieldContraseña = new javax.swing.JTextField();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelR1 = new javax.swing.JLabel();
        jLabelR2 = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonContinuar = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldR1.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldR1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldR1.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldR1.setBorder(null);
        jTextFieldR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldR1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 130, 20));

        jTextFieldP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldP1.setBorder(null);
        jPanel1.add(jTextFieldP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 270, 20));

        jTextFieldUsuario.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldUsuario.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 130, 20));

        jTextFieldP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldP2.setBorder(null);
        jPanel1.add(jTextFieldP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 270, 20));

        jTextFieldR2.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldR2.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldR2.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldR2.setBorder(null);
        jTextFieldR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldR2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 130, 20));

        jTextFieldContraseña.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldContraseña.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldContraseña.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldContraseña.setBorder(null);
        jTextFieldContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 130, 20));

        jLabelUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 150, 40));

        jLabelR1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 150, 40));

        jLabelR2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 150, 40));

        jLabelContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 150, 40));

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Botones Adicionales/Botón Buscar (Lupa).png"))); // NOI18N
        jButtonBuscar.setBorder(null);
        jButtonBuscar.setBorderPainted(false);
        jButtonBuscar.setContentAreaFilled(false);
        jButtonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 157, 30, 30));

        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Continuar (Verde).png"))); // NOI18N
        jButtonContinuar.setBorder(null);
        jButtonContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonContinuar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Continuar (Verde - Seleccionado).png"))); // NOI18N
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 610, 120, 30));

        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Cerrar.png"))); // NOI18N
        jButtonCerrar.setBorder(null);
        jButtonCerrar.setContentAreaFilled(false);
        jButtonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 10, 20));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Recuperar Contraseña.png"))); // NOI18N
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldR1ActionPerformed

    private void jTextFieldR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldR2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldR2ActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jTextFieldContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContraseñaActionPerformed

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        recuperarContraseña();
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        buscarUsuario();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void buscarUsuario(){
        if(jTextFieldUsuario.equals("")){
            JOptionPane.showMessageDialog(null,"Campo vacío. Por favor, Ingrese el nombre de usuario");
        }
        else{
            modelo.setNombre_usuario(jTextFieldUsuario.getText());
            
            if(modeloSQL.recuperarContraseña(modelo)){
                jTextFieldP1.setText(modelo.getPregunta1());
                jTextFieldP2.setText(modelo.getPregunta2());
            }
            else{
                JOptionPane.showMessageDialog(null,"Error en la busqueda");
            }
        }
    }
    
    private void recuperarContraseña(){
        String R1 = modelo.getRespuesta1();
        String R2 = modelo.getRespuesta2();
            
        if(R1.equals(jTextFieldR1.getText()) && R2.equals(jTextFieldR2.getText())){
            jTextFieldContraseña.setText(modelo.getContraseña());
        }
        if(!R1.equals(jTextFieldR1.getText())){
            JOptionPane.showMessageDialog(null,"Respuesta 1 Incorrecta");
        }
        if(!R2.equals(jTextFieldR2.getText())){
            JOptionPane.showMessageDialog(null,"Respuesta 2 Incorrecta");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonBuscar;
    public javax.swing.JButton jButtonCerrar;
    public javax.swing.JButton jButtonContinuar;
    public javax.swing.JLabel jLabelContraseña;
    public javax.swing.JLabel jLabelFondo;
    public javax.swing.JLabel jLabelR1;
    public javax.swing.JLabel jLabelR2;
    public javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextFieldContraseña;
    public javax.swing.JTextField jTextFieldP1;
    public javax.swing.JTextField jTextFieldP2;
    public javax.swing.JTextField jTextFieldR1;
    public javax.swing.JTextField jTextFieldR2;
    public javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
