
package Vista;

import Modelo.Administrador;
import Modelo.AdministradorSQL;
import Controlador.Fecha;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ARANAGA
 */
public class RegistroUsuario extends javax.swing.JFrame {
    
    Administrador modelo = new Administrador();
    AdministradorSQL modeloSQL = new AdministradorSQL();
    
    public RegistroUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imágenes/Ícono del Programa.png")).getImage());
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCerrar = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jComboBoxSexo = new javax.swing.JComboBox();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordConfirmar = new javax.swing.JPasswordField();
        jPassword = new javax.swing.JPasswordField();
        jTextFieldP1 = new javax.swing.JTextField();
        jTextFieldP2 = new javax.swing.JTextField();
        jTextFieldR1 = new javax.swing.JTextField();
        jTextFieldR2 = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelUsuario1 = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelContraseñaConfirmar = new javax.swing.JLabel();
        jLabelP1 = new javax.swing.JLabel();
        jLabelP2 = new javax.swing.JLabel();
        jLabelR1 = new javax.swing.JLabel();
        jLabelR2 = new javax.swing.JLabel();
        jButtonContinuar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(855, 643));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1. Inicio de Sesión/Botones/Botón Cerrar.png"))); // NOI18N
        jButtonCerrar.setContentAreaFilled(false);
        jButtonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, 10, 20));

        jTextFieldNombre.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldNombre.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 130, 20));

        jTextFieldApellido.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldApellido.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldApellido.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldApellido.setBorder(null);
        jTextFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 130, 20));

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Masculino", "Femenino", "Otro" }));
        jComboBoxSexo.setBorder(null);
        jPanel1.add(jComboBoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 150, -1));

        jTextFieldEmail.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldEmail.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldEmail.setText("usuario@gmail.com");
        jTextFieldEmail.setBorder(null);
        jTextFieldEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldEmailMouseClicked(evt);
            }
        });
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 130, 20));

        jTextFieldUsuario.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldUsuario.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 130, 20));

        jPasswordConfirmar.setBackground(new java.awt.Color(240, 240, 240));
        jPasswordConfirmar.setBorder(null);
        jPanel1.add(jPasswordConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 130, 20));

        jPassword.setBackground(new java.awt.Color(240, 240, 240));
        jPassword.setBorder(null);
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 120, 20));

        jTextFieldP1.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldP1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldP1.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldP1.setBorder(null);
        jTextFieldP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldP1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 130, 20));

        jTextFieldP2.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldP2.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldP2.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldP2.setBorder(null);
        jTextFieldP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldP2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 130, 20));

        jTextFieldR1.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldR1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldR1.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldR1.setBorder(null);
        jTextFieldR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldR1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 130, 20));

        jTextFieldR2.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldR2.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jTextFieldR2.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldR2.setBorder(null);
        jTextFieldR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldR2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, 130, 20));

        jLabelNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 150, 40));

        jLabelApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 150, 40));

        jLabelUsuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 150, 40));

        jLabelEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 150, 40));

        jLabelContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 150, 40));

        jLabelContraseñaConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelContraseñaConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 150, 40));

        jLabelP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 150, 40));

        jLabelP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 150, 40));

        jLabelR1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 150, 40));

        jLabelR2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Caja de Texto (Registros).png"))); // NOI18N
        jPanel1.add(jLabelR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 150, 40));

        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Botón Continuar (Verde).png"))); // NOI18N
        jButtonContinuar.setBorder(null);
        jButtonContinuar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Botones/Botón Continuar (Verde - Seleccionado).png"))); // NOI18N
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, 120, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Registros y Comprobaciones/Registro de Usuario.png"))); // NOI18N
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jTextFieldR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldR1ActionPerformed

    private void jTextFieldP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldP1ActionPerformed

    private void jTextFieldP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldP2ActionPerformed

    private void jTextFieldR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldR2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldR2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        validarRegistro();
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    private void jTextFieldEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldEmailMouseClicked
        jTextFieldEmail.setText(null);
    }//GEN-LAST:event_jTextFieldEmailMouseClicked

    private void validarRegistro(){
        String contraseña = new String(jPassword.getPassword());
        String contraseñaConfirmar = new String(jPasswordConfirmar.getPassword());
        int usuarioExistente = 0;
        
        if(jTextFieldNombre.getText().equals("") || contraseña.equals("") || contraseñaConfirmar.equals("") ||
            jTextFieldApellido.getText().equals("") ||  jTextFieldEmail.getText().equals("") || 
            jTextFieldP1.getText().equals("") || jTextFieldP2.getText().equals("") ||  
            jTextFieldR1.getText().equals("") || jTextFieldR2.getText().equals("")
                || jComboBoxSexo.getSelectedItem().toString().equals("Seleccione")){
            
            JOptionPane.showMessageDialog(null,"Hay campos vacios. Llene todos los campos");
        }
        else{
            usuarioExistente = modeloSQL.existeUsuario(jTextFieldUsuario.getText());
            System.out.println(jTextFieldUsuario.getText());
            System.out.println(usuarioExistente);
            if(usuarioExistente == 0){
                if(contraseña.equals(contraseñaConfirmar)){  
                    registrarUsuario(contraseña);
                }        
                else{
                    JOptionPane.showMessageDialog(null,"Error: Contraseñas distintas");
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"El nombre de usuario que ingreso ya existe. Intente nuevamente");
            }
        }    
    }
    
    private void registrarUsuario(String contraseña){
        Fecha fecha = new Fecha();
        
        //Tabla Administrador
        modelo.setNombre(jTextFieldNombre.getText());
        modelo.setApellido(jTextFieldApellido.getText());
        modelo.setSexo(String.valueOf(jComboBoxSexo.getSelectedItem()));
        modelo.setEmail(jTextFieldEmail.getText());
        modelo.setNombre_usuario(jTextFieldUsuario.getText());
        modelo.setContraseña(contraseña);
        modelo.setPregunta1(jTextFieldP1.getText());
        modelo.setPregunta2(jTextFieldP2.getText());
        modelo.setRespuesta1(jTextFieldR1.getText());
        modelo.setRespuesta2(jTextFieldR2.getText());

        if(modeloSQL.registrar(modelo)){
            modeloSQL.actualizarEntrada(fecha.obtenerFechaActual(), modelo.getNombre_usuario());
            JOptionPane.showMessageDialog(null,"Registro finalizado con éxito");
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null,"Error al registrar");
        }
    }
                    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JComboBox jComboBoxSexo;
    public javax.swing.JLabel jLabelApellido;
    public javax.swing.JLabel jLabelContraseña;
    public javax.swing.JLabel jLabelContraseñaConfirmar;
    public javax.swing.JLabel jLabelEmail;
    public javax.swing.JLabel jLabelFondo;
    public javax.swing.JLabel jLabelNombre;
    public javax.swing.JLabel jLabelP1;
    public javax.swing.JLabel jLabelP2;
    public javax.swing.JLabel jLabelR1;
    public javax.swing.JLabel jLabelR2;
    public javax.swing.JLabel jLabelUsuario1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPasswordField jPassword;
    public javax.swing.JPasswordField jPasswordConfirmar;
    public javax.swing.JTextField jTextFieldApellido;
    public javax.swing.JTextField jTextFieldEmail;
    public javax.swing.JTextField jTextFieldNombre;
    public javax.swing.JTextField jTextFieldP1;
    public javax.swing.JTextField jTextFieldP2;
    public javax.swing.JTextField jTextFieldR1;
    public javax.swing.JTextField jTextFieldR2;
    public javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
